version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:    # updates to project to our docker container in real-time. do need to restart docker to see changes
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
